### ISSUE TITLE
bump middleware to v1.4.0

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/owncloud-test-middleware#104]
After the new release `v1.4.0`, bump middleware version in:
- [x] web https://github.com/owncloud/web/pull/6442
- [x] desktop-client https://github.com/owncloud/client/pull/9447

**Comment by Talank** [comment]
middleware version has been bumped in both web and desktio-client.

**Comment by pascalwengerter** [comment]
Could you add bumping it in the oCIS CI to your templates? Having me go on a hunt why CI is failing and then coming to the conclusion feels unnecessary ;) (https://github.com/owncloud/ocis/pull/3437/commits/94d77ce813a62a728af05e8fd11b5f75e395152c)

**Comment by kiranparajuli589** [comment]
sure @pascalwengerter, we'll keep this in mind for further releases. sorry for the inconvenience :).
