### ISSUE TITLE
Refactor occ command related steps for ocis

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/owncloud-test-middleware#123]
occ command in oC10 is used to set system-wide settings in oC10. Many of those things may be implemented in oCIS, but the way that the system-wide setting is done by the system administrator in oCIS will be different. Steps running occ command should be refactor for ocis.
For better understanding visit this issue: https://github.com/owncloud/ocis/issues/1317#issuecomment-895700367
https://github.com/owncloud/ocis/issues/1328

**Comment by SwikritiT** [comment]
The related PR has been merged so closing this issue
