### ISSUE TITLE
endpoint to retrieve state of the scenario

### ISSUE THREAD

**Issue by individual-it** [owncloud/owncloud-test-middleware#16]
we need a way to retrieve some information from the middleware to use them in the test-runner
e.g. it would be handy if the test-runner could find out the password of the created user and would not need to mention it see https://github.com/owncloud/client/pull/8287#issuecomment-795111587
we could have a general endpoint that sends back various information. For the start it would send back the user info of created users (password, displayname, etc) and we can add more to it as we need it

**Comment by phil-davis** [comment]
@kiranparajuli589 this issue is in the "Review in Progress" column. But #35 was already merged.
Can this issue be closed?

**Comment by kiranparajuli589** [comment]
yes its done
