### ISSUE TITLE
[QA] pass information related to user through middleware

### ISSUE THREAD

**Issue by swoichha** [owncloud/owncloud-test-middleware#42]
## Description
In desktop-client we get data like display-name, password, email, etc. related to a user using global default user values like here 

https://github.com/owncloud/client/blob/2abdd8c8e373dbe9c8e9ab5292f14888c456ef34/test/gui/shared/steps/steps.py#L35-L51

## TO-DO:
As mentioned in https://github.com/owncloud/client/pull/8553#discussion_r613983886 these information should come out of the middleware
Also see: https://github.com/owncloud/owncloud-test-middleware/issues/16

**Comment by kiranparajuli589** [comment]
this constant https://github.com/owncloud/client/pull/8553#discussion_r613983886 form the client should be removed as the user creating is done in middleware, client does not need this.
to get the test's current status , `state` endpoint of middleware should be requested which provides the created users and groups details during the test run.

**Comment by swoichha** [comment]
Looks like it has been done in https://github.com/owncloud/owncloud-test-middleware/pull/35. So, we can close this issue.
