### ISSUE TITLE
Refactor to set skeletondir as an empty string with "without skeleton" step

### ISSUE THREAD

**Issue by saw-jan** [owncloud/owncloud-test-middleware#50]
Now, with PR https://github.com/owncloud/core/pull/39230/files, we can set skeletondir as an empty string. So no need to set a path to an empty folder when using `without skeleton` step.

**Comment by phil-davis** [comment]
This will be fine in the middleware. Clients that use it are testing against the current oC10 master (which will become 10.9 release), which has the "feature".

If there are CI pipelines that still need to test a client against ownCloud core 10.8.0 then we have to think more about when or how to do this.

**Comment by saw-jan** [comment]
I have moved it to the Backlog as we need to have some discussion on how to implement it (an approach that will be backward compatible).

**Comment by phil-davis** [comment]
We can leave this some more months, until after the next core release, and we confirm that testing against 10.8 or earlier via middleware is no longer needed.

**Comment by phil-davis** [comment]
Still blocked - core 10.10.0 is about to be released. Other "themed/derivative" releases of core will soon all be on either 10.9.1 or 10.10.0 of core. After that is the case, then we will not have to think about backward-compatibility.

**Comment by kiranparajuli589** [comment]
oC/core has reached v10.11.xx. can we move this forward? @phil-davis

**Comment by phil-davis** [comment]
And core latest will become 10.12 "soon".
Moved to the ordinary backlog. @saw-jan IMO this can be looked at again.

**Comment by SwikritiT** [comment]
The core is now `10.12`. Maybe we can move forward with this?

cc: @saw-jan @phil-davis

**Comment by phil-davis** [comment]
Yes, this can be assigned to somebody. The middleware will only be used to test against core oC 10.11 or 10.12 or master.

**Comment by saw-jan** [comment]
won't be happening.
