### ISSUE TITLE
Add more tests and/or lint

### ISSUE THREAD

**Issue by phil-davis** [owncloud/owncloud-test-middleware#78]
We had this problem today that `replaceAll` was used in some code. But `replaceAll` is not supported until nodejs 15 or later. See PR #76 for some details.

It would be nice to know in CI if new code uses some nodejs feature that does not exist in the nodejs version being used in the docker image. I tried running the lint with nodejs 14, but lint still passed - see PR #77 

Maybe there is some other code analysis tool that will quickly tell us about node version compatibility problems?

Or we make more unit and/or integration tests that will actually execute each piece of code. That should cause fails when executed with a nodejs version that is too old for the code.

For discussion...

**Comment by phil-davis** [comment]
CC @kiranparajuli589 @Talank @SwikritiT @SwikritiT @individual-it

**Comment by individual-it** [comment]
I think we should add more tests, that should not be too hard. If there are situations we cannot tests with unit tests, even adding e2e API tests would be OK here

**Comment by kiranparajuli589** [comment]
Findings so far:

Did some research on this, find out that eslint does not care of this kind of issue. See https://github.com/eslint/eslint/discussions/16176#discussioncomment-3306329

But there is an eslint plugin called `eslint-plugin-n` which has some implementations to detect such cases. See https://github.com/weiran-zsd/eslint-plugin-node/issues/43#issuecomment-1209079981

One another approach can be the use of typeScript where we can configure the node base as https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#tsconfig-bases.

**Comment by saw-jan** [comment]
In PR #128, I have made the node and eslint parser versions strict so that the incompatible versions and codes are reported. With this, we can get early feedback in ci as well as locally.

**Comment by kiranparajuli589** [comment]
@saw-jan can we detect issues like the following now with eslint?

> We had this problem today that `replaceAll` was used in some code. But `replaceAll` is not supported until NodeJS 15 or later.

**Comment by saw-jan** [comment]
Yeah, 99% sure :smile: 
node >16.3 support 100% of ecma2021 features + some ecma2022 features.
And if a feature only available from ecma2022 is used then eslint should report that

**Comment by saw-jan** [comment]
With PR https://github.com/owncloud/owncloud-test-middleware/pull/128, there is a restriction to the js features we can use in the code and the eslint will report that.
Also, the incompatible version of node will be reported (which was the main concern of this issue)

As per the tests, we could think of any better way. The problem with `replaceAll` came from the stepDefs code and that code only runs when there is `/execute` request with the provided step. If we are to test this then we might need to create API test for each step available, but I have no idea how it will benefit us.

**Comment by kiranparajuli589** [comment]
Yes, for the code in stepDefs, I think adding API acceptance tests would be good.

**Comment by saw-jan** [comment]
We will need to have a thorough discussion on how to add those API tests and also discuss the feasibility and benefits of those tests.

**Comment by individual-it** [comment]
I think adding more API tests for this is over engineering. Let's close this for now as a lot of issues should be caught by the linter
