### ISSUE TITLE
pin version of middleware

### ISSUE THREAD

**Issue by phil-davis** [owncloud/owncloud-test-middleware#79]
We could allow the version of the middleware to be pinned by the various application testing that uses it - for example web and desktop-client. That would allow us to develop the middleware, but the consumers of the middleware can use a pinned/tagged version and update when they want. It would avoid the problems like happened last night, that new changes in the middleware accidentally broke CI in web.

To do this, we would have to create some tag naming system in this middleware repo.

Discussion please...

**Comment by phil-davis** [comment]
CC: @kiranparajuli589 @Talank @saw-jan @SwikritiT @individual-it

**Comment by individual-it** [comment]
I would suggest that introduce sem-versioning in this repo and whenever a new release happens we add a git tag and make drone to build a new docker image with that tag

**Comment by SwikritiT** [comment]
This has been done so closing this issue now.
