### ISSUE TITLE
Release 1.2.1

### ISSUE THREAD

**Issue by phil-davis** [owncloud/owncloud-test-middleware#91]
https://github.com/owncloud/owncloud-test-middleware/compare/v1.2.0...main

PRs included are:
#89 Tidy some code
#90 Retry download if resource is locked

These are both fixes or refactoring, no really new features. So it can be a patch release.

**Comment by saw-jan** [comment]
Released https://github.com/owncloud/owncloud-test-middleware/releases/tag/1.2.1
